language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly


  before_script: composer require atoum/atoum
script: vendor/bin/atoum

  install: php vendor/vendors.php

before_script: phpenv config-add myconfig.ini